import {
  hmCategorySlug,
  hmCategorySlugCandidates,
  humanizeNewsCategorySlug,
  splitCamelCaseCategoryToken,
} from "./hmCategorySlug";
import type { HmBreakingRssFeedRow, HmNewsHomeModuleCategorySlugs, HmNewsHomeModuleId, PortalHybridRssFeed } from "./newsSiteLayout";
import { resolveHmBreakingRssCategoryKey } from "./newsSiteLayout";

export type HmUnifiedCategoryOption = {
  slug: string;
  name: string;
};

/** Anasayfa haber kutularında otomatik kategori dağıtımına dahil modüller (tek kutu = tek slug). */
export const HOME_NEWS_AUTO_CATEGORY_MODULES = new Set<HmNewsHomeModuleId>([
  "portal3ThemeBlock",
  "esenThemeBlock",
  "leadListSidebar",
  "ahenkAnkaraGrid",
  "ahenkGundemLeadSide",
  "ahenkSporGrid",
  "sporModule",
  "ahenkDunyaBlock",
  "ahenkEkonomiGrid",
  "ahenkSonEklenenler",
  "ahenkPopulerHaberler",
]);

/** Birden fazla kategori kutusu gösteren modüller — tek slug filtresi uygulanmaz. */
export const HOME_NEWS_MULTI_CATEGORY_SECTION_MODULES = new Set<HmNewsHomeModuleId>(["yekpareKategorilerKutusu"]);

/** Editör «Kutu kategorileri» sekmesinde slug atanabilir tüm haber kutuları. */
export const HM_NEWS_HOME_MODULE_CATEGORY_ASSIGNABLE: HmNewsHomeModuleId[] = [
  ...Array.from(HOME_NEWS_AUTO_CATEGORY_MODULES),
  "latestGrid",
  "featuredCategoryStrip",
];

export function normalizeHomeModuleCategorySlug(value: string): string {
  return hmCategorySlug(value);
}

/** Görünen ad karşılaştırması — egitim/Eşitim, spor/Spor tekilleştirme. */
export function normalizeCategoryDisplayName(name: unknown): string {
  return String(name ?? "")
    .trim()
    .toLocaleLowerCase("tr-TR")
    .replace(/ı/g, "i")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function buildCategorySlugCandidates(slugRaw: unknown, nameRaw: unknown): string[] {
  const seen = new Set<string>();
  const push = (value: unknown) => {
    for (const slug of hmCategorySlugCandidates(value)) {
      if (slug) seen.add(slug);
    }
    const camel = splitCamelCaseCategoryToken(value);
    if (camel !== String(value ?? "").trim()) {
      for (const slug of hmCategorySlugCandidates(camel)) {
        if (slug) seen.add(slug);
      }
    }
  };
  push(slugRaw);
  push(nameRaw);
  return Array.from(seen);
}

function isAutoGeneratedCategorySlug(slug: string): boolean {
  if (/^yeni-kategori(?:-|$)/.test(slug)) return true;
  const trimmed = slug.replace(/-[a-z0-9]{5,}$/i, "");
  return trimmed !== slug && trimmed.length >= 3;
}

function preferCanonicalCategorySlug(slugs: readonly string[]): string {
  if (slugs.length === 0) return "";
  return [...slugs].sort((a, b) => {
    const score = (slug: string) => {
      let value = 0;
      if (!isAutoGeneratedCategorySlug(slug)) value += 100;
      if (slug.includes("-") && !isAutoGeneratedCategorySlug(slug)) value += 10;
      value -= slug.length * 0.05;
      return value;
    };
    return score(b) - score(a);
  })[0]!;
}

type UnifiedCategoryAccumulator = {
  slug: string;
  name: string;
  fromSite: boolean;
};

/**
 * Site + RSS + portal hibrit kaynaklarından tek canonical slug listesi.
 * Aynı kategori (Ankara/ankara, egitim/Eşitim, savunmaSanayi/Savunma Sanayi) tek satır.
 */
export function buildUnifiedHomeCategoryOptions(opts: {
  siteCategories?: Array<{ slug?: string | null; name?: string | null }>;
  rssFeedRows?: Array<Pick<HmBreakingRssFeedRow, "id" | "label" | "categoryKey">>;
  portalHybridFeeds?: Array<Pick<PortalHybridRssFeed, "categorySlug" | "label">>;
}): HmUnifiedCategoryOption[] {
  const merged = new Map<string, UnifiedCategoryAccumulator>();
  const slugAlias = new Map<string, string>();
  const nameIndex = new Map<string, string>();

  const resolveTargetSlug = (candidates: string[], normName: string): string => {
    for (const candidate of candidates) {
      const aliased = slugAlias.get(candidate) ?? candidate;
      if (merged.has(aliased)) return aliased;
    }
    if (normName && nameIndex.has(normName)) return nameIndex.get(normName)!;
    return preferCanonicalCategorySlug(candidates);
  };

  const registerAliases = (targetSlug: string, candidates: string[], normName: string) => {
    for (const candidate of candidates) slugAlias.set(candidate, targetSlug);
    if (normName) nameIndex.set(normName, targetSlug);
  };

  const ingest = (slugRaw: unknown, nameRaw: unknown, fromSite: boolean) => {
    const candidates = buildCategorySlugCandidates(slugRaw, nameRaw);
    if (candidates.length === 0) return;

    const displayName =
      String(nameRaw ?? "").trim() ||
      String(slugRaw ?? "").trim() ||
      humanizeNewsCategorySlug(candidates[0]!);
    const normName = normalizeCategoryDisplayName(displayName);
    const targetSlug = resolveTargetSlug(candidates, normName);
    registerAliases(targetSlug, candidates, normName);

    const existing = merged.get(targetSlug);
    if (!existing) {
      merged.set(targetSlug, {
        slug: targetSlug,
        name: displayName,
        fromSite,
      });
      return;
    }

    if (fromSite && displayName) {
      merged.set(targetSlug, { slug: targetSlug, name: displayName, fromSite: true });
      return;
    }

    if (!existing.fromSite && displayName && displayName.length >= existing.name.length) {
      merged.set(targetSlug, { slug: targetSlug, name: displayName, fromSite: false });
    }
  };

  for (const cat of opts.siteCategories ?? []) {
    ingest(cat.slug, cat.name, true);
  }
  for (const row of opts.rssFeedRows ?? []) {
    ingest(resolveHmBreakingRssCategoryKey(row), row.label, false);
  }
  for (const row of opts.portalHybridFeeds ?? []) {
    ingest(row.categorySlug, row.label, false);
  }

  return Array.from(merged.values())
    .map(({ slug, name }) => ({ slug, name: name || humanizeNewsCategorySlug(slug) }))
    .sort((a, b) => a.name.localeCompare(b.name, "tr-TR"));
}

/** Site + RSS haber öşesi tek canonical slug ile eşleşir. */
export function newsItemMatchesCategorySlug(item: unknown, categorySlug: string): boolean {
  const target = hmCategorySlug(categorySlug);
  if (!target) return true;
  const row = item as { categorySlug?: unknown; categoryName?: unknown; feedLabel?: unknown };
  const candidates = hmCategorySlugCandidates(row?.categorySlug, row?.categoryName, row?.feedLabel);
  if (candidates.includes(target)) return true;

  const targetName = normalizeCategoryDisplayName(humanizeNewsCategorySlug(target));
  const itemName = normalizeCategoryDisplayName(
    row?.categoryName ?? row?.feedLabel ?? humanizeNewsCategorySlug(String(row?.categorySlug ?? "")),
  );
  return !!targetName && targetName === itemName;
}

export function buildHomeModuleCategoryCandidates(opts: {
  tabStripSlugs?: readonly string[];
  sectionSlugs?: readonly string[];
  siteCategories?: Array<{ slug?: string | null; name?: string | null }>;
  newsItems?: unknown[];
}): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  const push = (...values: unknown[]) => {
    const slug = hmCategorySlug(...values);
    if (!slug || seen.has(slug)) return;
    seen.add(slug);
    out.push(slug);
  };

  for (const slug of opts.tabStripSlugs ?? []) push(slug);
  for (const slug of opts.sectionSlugs ?? []) push(slug);
  for (const cat of opts.siteCategories ?? []) push(cat.slug, cat.name);
  for (const item of opts.newsItems ?? []) {
    const row = item as { categorySlug?: unknown; categoryName?: unknown; feedLabel?: unknown };
    push(row.categorySlug, row.categoryName, row.feedLabel);
  }
  return out;
}

/** Manuel seçim yoksa her kutu farklı kategori slug'ı alır (yeterli aday varsa). */
export function resolveAutomaticHomeModuleCategorySlugs(opts: {
  orderedModules: readonly HmNewsHomeModuleId[];
  manualSlugs?: HmNewsHomeModuleCategorySlugs | null;
  autoAssignableModules?: ReadonlySet<HmNewsHomeModuleId>;
  candidates: readonly string[];
}): Partial<Record<HmNewsHomeModuleId, string>> {
  const assignable = opts.autoAssignableModules ?? HOME_NEWS_AUTO_CATEGORY_MODULES;
  const normalizedCandidates: string[] = [];
  const seen = new Set<string>();
  for (const raw of Array.isArray(opts.candidates) ? opts.candidates : []) {
    const slug = hmCategorySlug(raw);
    if (!slug || seen.has(slug)) continue;
    seen.add(slug);
    normalizedCandidates.push(slug);
  }
  if (normalizedCandidates.length === 0) return {};

  const manual = opts.manualSlugs ?? {};
  const out: Partial<Record<HmNewsHomeModuleId, string>> = {};
  const usedAuto = new Set<string>();
  let candidateIdx = 0;

  const orderedModules: readonly HmNewsHomeModuleId[] = Array.isArray(opts.orderedModules)
    ? opts.orderedModules
    : [];

  for (const moduleId of orderedModules) {
    if (!assignable.has(moduleId)) continue;
    if (hmCategorySlug(manual[moduleId])) continue;

    let picked = "";
    for (let attempt = 0; attempt < normalizedCandidates.length; attempt += 1) {
      const candidate = normalizedCandidates[(candidateIdx + attempt) % normalizedCandidates.length];
      if (!usedAuto.has(candidate)) {
        picked = candidate;
        candidateIdx = (candidateIdx + attempt + 1) % normalizedCandidates.length;
        break;
      }
    }
    if (!picked) {
      picked = normalizedCandidates[candidateIdx % normalizedCandidates.length];
      candidateIdx += 1;
    }
    usedAuto.add(picked);
    out[moduleId] = picked;
  }
  return out;
}

export function normalizeCategorySlugList(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of raw) {
    const slug = hmCategorySlug(item);
    if (!slug || seen.has(slug)) continue;
    seen.add(slug);
    out.push(slug);
  }
  return out;
}

/**
 * Son Haberler (latestGrid) modülünün açılış sekmesi.
 * Yalnızca editörün seçtiği slug kullanılır; boş = «Tümü» sekmesi.
 */
export function resolveLatestGridOpeningCategorySlug(opts: {
  manualSlug?: string | null;
  autoSlug?: string | null;
  tabStripSlugs?: readonly string[];
  sectionSlugs?: readonly string[];
}): string {
  void opts.autoSlug;
  void opts.tabStripSlugs;
  void opts.sectionSlugs;
  return hmCategorySlug(opts.manualSlug);
}

/** Manuel slug sırasına göre kategori bölümlerini seçer (renkli şerit vb.). */
export function pickCategorySectionsBySlugs<T extends { slug: string }>(
  sections: readonly T[] | null | undefined,
  orderedSlugs: readonly string[] | null | undefined,
): T[] {
  const safeSections = Array.isArray(sections) ? sections : [];
  const safeOrderedSlugs = Array.isArray(orderedSlugs) ? orderedSlugs : [];
  if (safeOrderedSlugs.length === 0) return [...safeSections];
  const bySlug = new Map<string, T>();
  for (const section of safeSections) {
    const slug = hmCategorySlug(section.slug);
    if (slug && !bySlug.has(slug)) bySlug.set(slug, section);
  }
  const out: T[] = [];
  for (const raw of safeOrderedSlugs) {
    const slug = hmCategorySlug(raw);
    const row = slug ? bySlug.get(slug) : undefined;
    if (row) out.push(row);
  }
  return out;
}

