/** Keşfet — Popüler Aramalar (varsayılan; API yoksa kullanılır) */
export type KesfetDiscoverSubcategory = {
  id: string;
  name: string;
  slug: string;
  googlePlaceType?: string | null;
  googleKeyword?: string | null;
};

export type KesfetDiscoverGroup = {
  id: string;
  key: string;
  label: string;
  icon: string;
  subcategories: KesfetDiscoverSubcategory[];
};

function sub(group: string, names: string[]): KesfetDiscoverSubcategory[] {
  return names.map((name) => ({
    id: `${group}-${name.toLowerCase().replace(/[^a-z0-9ğüşıöçĞÜŞİÖÇ]+/gi, "-").replace(/-+/g, "-").replace(/^-|-$/g, "")}`,
    name,
    slug: name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/ı/g, "i")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, ""),
    googleKeyword: name,
  }));
}

export const KESFET_DISCOVER_GROUPS: KesfetDiscoverGroup[] = [
  {
    id: "saglik",
    key: "saglik",
    label: "Sağlık",
    icon: "⚕️",
    subcategories: sub("saglik", [
      "Aile Hekimleri",
      "Akupunktur",
      "Çocuk Doktorları",
      "Dahiliye Doktorları",
      "Dermatolog",
      "Diş Hekimleri",
      "Diyetisyenler",
      "Eczane",
      "Evde Bakım Hizmetleri",
      "Genel Cerrahi Doktorları",
      "Göz Doktorları",
      "Göz Hastaneleri ve Klinikleri",
      "Hastane",
      "Kulak Burun Boğaz Doktorları",
      "Poliklinikler",
    ]),
  },
  {
    id: "ev",
    key: "ev",
    label: "Ev",
    icon: "🏠",
    subcategories: sub("ev", [
      "Antikacılar ve Antika Tamiri",
      "Bahçe Düzenleme ve Peyzaj",
      "Bahçe Mobilyaları",
      "Beyaz Eşya ve Elektronik Mağazaları",
      "Cam Balkon",
      "Çelik Kapı",
      "Çeyiz Mağazaları",
      "Çocuk-Bebek Mobilya ve Eşyaları",
      "Duşakabin",
      "Duvar Kağıdı",
      "Ev Tekstili",
      "Evden Eve Nakliyat",
      "Halı Yıkama",
      "Hazır Mutfak ve Banyo",
      "Koltuk Döşeme ve Döşemelik Kumaş",
      "Küçük Ev Aletleri",
      "Perde ve Jaluzi",
      "Su Bayileri",
      "Yatak ve Baza",
    ]),
  },
  {
    id: "hizmetler",
    key: "hizmetler",
    label: "Hizmetler",
    icon: "🛠️",
    subcategories: sub("hizmetler", [
      "Ambulans Hizmetleri",
      "Arabuluculuk",
      "Bankalar",
      "Boyacılar",
      "Çay Bahçesi",
      "Çay Ocağı",
      "Çilingir ve Anahtarcılar",
      "Dış Cephe Kaplama",
      "Doğal Gaz Tesisatçıları",
      "Elektrikçiler ve Elektrik Malzemeleri",
      "Gümrük Müşavirliği",
      "İnşaat Mühendisliği ve Müteahhitlik",
      "Kargo-Kutu ve Oluklu Mukavva",
      "Menajerlik Ajansları",
      "Mobilya Boyama",
      "Noter",
      "Oto Tamircileri",
      "Psikoteknik Kursu",
      "Sanal Ofis",
      "Serbest Muhasebeci Mali Müşavirler",
      "Sıhhi Tesisatçı",
      "SRC Kursu",
      "Temizlik Şirketleri",
      "Terziler",
      "Yeminli Mali Müşavirler",
      "Yol Yardım-Oto Kurtarma",
    ]),
  },
  {
    id: "egitim",
    key: "egitim",
    label: "Eğitim",
    icon: "📚",
    subcategories: sub("egitim", [
      "Özel Okullar",
      "Özel Sürücü Kursları (MTSK / Ehliyet)",
      "SRC Psikoteknik Merkezleri",
      "Sınava Hazırlık Kursları",
      "Eğitim Danışmanlığı",
      "Yabancı Dil Kursları",
      "Yurtdışı Eğitim Danışmanlığı",
      "Rehabilitasyon Merkezleri",
      "Destek Merkezleri",
      "Terapi Merkezleri",
      "Kişisel Gelişim Kursları",
      "Sertifika Merkezleri",
      "Bilişim Akademileri",
      "Robotik Kodlama",
      "Online Eğitim Platformları",
      "Uzaktan Öğretim Kursları",
      "Kız ve Erkek Öğrenci Yurtları",
    ]),
  },
  {
    id: "eglence",
    key: "eglence",
    label: "Eğlence",
    icon: "🎭",
    subcategories: sub("eglence", [
      "Beach Club ve Plajlar",
      "Bilardo Salonları",
      "Birahaneler",
      "Bowling Salonları",
      "Cd-Dvd-Bilgisayar Oyun Satışı ve Kiralama",
      "Düğün Salonları",
      "Gece Kulübü ve Barlar",
      "Gösteri Merkezleri",
      "Hayvanat Bahçeleri",
      "İnternet Kafeler ve Oyun Salonları",
      "Lunapark ve Eğlence Parkları",
      "Meyhaneler",
      "Paintball",
      "Parklar ve Oyun Alanları",
      "Parti ve Düğün Organizasyonu",
      "Restoranlar",
      "Şarap Evleri",
      "Sinemalar",
      "Tiyatrolar",
      "Türkü Evleri",
    ]),
  },
  {
    id: "otomotiv",
    key: "otomotiv",
    label: "Otomotiv",
    icon: "🚗",
    subcategories: sub("otomotiv", [
      "Galeri",
      "2. El",
      "Sıfır Araç",
      "Yedek Parça",
      "Çıkma Parça",
      "Oto Yıkama",
      "Oto Klima Servisi",
      "Oto Mekanik / Motor Tamir",
      "Oto Elektrikçi",
      "Oto Kaportacı",
      "Egzozcu",
      "Lastikçi",
      "Rot-Balans",
      "Periyodik Bakım Merkezi",
      "Oto Ekspertiz",
      "Oto Çekici / Kurtarıcı",
      "LPG Servisi",
    ]),
  },
  {
    id: "siparis",
    key: "siparis",
    label: "Sipariş",
    icon: "🍽️",
    subcategories: sub("siparis", [
      "Yemek",
      "Market",
      "Fast Food",
      "Kafe",
      "Pastane",
      "Manav",
      "Kasap",
      "Kurye",
    ]),
  },
  {
    id: "servis",
    key: "servis",
    label: "Servis",
    icon: "🛠️",
    subcategories: sub("servis", [
      "VIP Transfer",
      "Tamir",
      "Temizlik",
      "Boyacı",
      "Elektrikçi",
      "Tesisatçı",
      "Klima Servisi",
      "Güvenlik",
      "Taşımacılık",
    ]),
  },
  {
    id: "insaat",
    key: "insaat",
    label: "İnşaat",
    icon: "🏗️",
    subcategories: [],
  },
  {
    id: "seyahat",
    key: "seyahat",
    label: "Seyahat",
    icon: "🌍",
    subcategories: sub("seyahat", [
      "Otel",
      "Tur",
      "Uçak",
      "Villa",
      "Yat",
      "Araç Kiralama",
      "Boğaz Turu ve Mavi Tur",
      "Devre Mülk Hizmetleri",
      "Duty Free Alışveriş Noktaları",
      "Evcil Hayvan Pansiyonları",
      "Havaalanları",
      "Havayolları",
      "Kampingler",
      "Limanlar",
      "Marinalar",
      "Otobüs Terminalleri",
      "Otobüs ve Minibüs Kiralama",
      "Tekne Kiralama",
      "Tren İstasyonları",
      "Tur Şirketleri",
      "Turist Danışma Büroları",
      "Vapur ve Feribot İskeleleri",
      "Vize Takip Firmaları",
    ]),
  },
  {
    id: "ulasim",
    key: "ulasim",
    label: "Ulaşım",
    icon: "🚕",
    subcategories: sub("ulasim", [
      "Kargo",
      "Paket",
      "Taksi",
      "Dolmuş",
      "Kurye",
      "Çekici",
      "Nakliyat",
      "Rent a Car",
    ]),
  },
];
