export {
  isYektubeV2Enabled,
  isYektubeDedicatedHost,
  yektubeRouterBaseForHost,
  yektubeDedicatedPublicPath,
  yektubeDedicatedTopLevelPaths,
  YEKTUBE_DEDICATED_MUSIC_PATH,
  YEKTUBE_DEDICATED_KIDS_PATH,
  YEKTUBE_DEDICATED_LEGACY_PUBLIC_PATH,
  mapPathToYektubeV2,
  mapLegacyYektubePathToCanonical,
  mapToYektubeDedicatedUrl,
  mapPathToYektubePortal,
  mapToYektubePublicUrl,
  mapToHmYektubeEmbedUrl,
  isYektubeCanonicalRedirectEnabled,
  YEKTUBE_V2_PUBLIC_BASE,
  YEKTUBE_ORIGIN,
} from "@workspace/yektube-core";
