import type { TourismListingRow } from "./normalizeTourismListing";

const BC: TourismListingRow[] = [
  {
    "id": -9000,
    "type": "villa",
    "title": "Beyoğlu Lüks Stüdyo Daire",
    "slug": "bc-beyoglu-luks-studyo",
    "city": "İstanbul",
    "image_url": "/assets/turizm-bc/space/space-1.jpg",
    "price": "2850",
    "sale_price": "2490",
    "price_unit": "gece",
    "star_rating": null,
    "rating": 4.7,
    "review_count": 64,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9001,
    "type": "villa",
    "title": "Kaş Deniz Manzaralı Apart",
    "slug": "bc-kas-deniz-manzarali-apart",
    "city": "Antalya",
    "image_url": "/assets/turizm-bc/space/space-2.jpg",
    "price": "4200",
    "sale_price": null,
    "price_unit": "gece",
    "star_rating": null,
    "rating": 4.8,
    "review_count": 41,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9002,
    "type": "villa",
    "title": "Bodrum Şık Loft Villa",
    "slug": "bc-bodrum-sik-loft-villa",
    "city": "Muğla",
    "image_url": "/assets/turizm-bc/space/space-3.jpg",
    "price": "6500",
    "sale_price": "5990",
    "price_unit": "gece",
    "star_rating": null,
    "rating": 4.9,
    "review_count": 29,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9003,
    "type": "villa",
    "title": "Fethiye Deniz Manzaralı Villa",
    "slug": "bc-fethiye-deniz-manzarali-villa",
    "city": "Muğla",
    "image_url": "/assets/turizm-bc/space/space-4.jpg",
    "price": "7800",
    "sale_price": null,
    "price_unit": "gece",
    "star_rating": null,
    "rating": 4.8,
    "review_count": 53,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9004,
    "type": "villa",
    "title": "Kapadokya Taş Ev",
    "slug": "bc-kapadokya-tas-ev",
    "city": "Nevşehir",
    "image_url": "/assets/turizm-bc/space/space-5.jpg",
    "price": "3600",
    "sale_price": "3290",
    "price_unit": "gece",
    "star_rating": null,
    "rating": 4.7,
    "review_count": 72,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9005,
    "type": "car",
    "title": "BMW X6 Facelift",
    "slug": "bc-bmw-x6-facelift",
    "city": "İstanbul",
    "image_url": "/assets/turizm-bc/car/car-1.jpg",
    "price": "2850",
    "sale_price": "2490",
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.6,
    "review_count": 118,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9006,
    "type": "car",
    "title": "Honda Clarity",
    "slug": "bc-honda-clarity",
    "city": "Antalya",
    "image_url": "/assets/turizm-bc/car/car-2.jpg",
    "price": "1450",
    "sale_price": null,
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.5,
    "review_count": 89,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9007,
    "type": "car",
    "title": "BMW M6 Gran Coupe",
    "slug": "bc-bmw-m6-gran-coupe",
    "city": "İzmir",
    "image_url": "/assets/turizm-bc/car/car-3.jpg",
    "price": "3200",
    "sale_price": "2890",
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.8,
    "review_count": 44,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9008,
    "type": "car",
    "title": "Volkswagen Golf",
    "slug": "bc-volkswagen-golf",
    "city": "Ankara",
    "image_url": "/assets/turizm-bc/car/car-4.jpg",
    "price": "1190",
    "sale_price": "990",
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.4,
    "review_count": 132,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9009,
    "type": "car",
    "title": "Mercedes Vito",
    "slug": "bc-mercedes-vito",
    "city": "İstanbul",
    "image_url": "/assets/turizm-bc/car/car-5.jpg",
    "price": "2100",
    "sale_price": null,
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.7,
    "review_count": 67,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9010,
    "type": "boat",
    "title": "Boğaz Kruvaziyer Yatı",
    "slug": "bc-bogaz-kruvaziyer-yati",
    "city": "İstanbul",
    "image_url": "/assets/turizm-bc/boat/boat-1.jpg",
    "price": "18500",
    "sale_price": "16900",
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.9,
    "review_count": 76,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9011,
    "type": "boat",
    "title": "Bodrum Yaz Esintisi",
    "slug": "bc-bodrum-yaz-esintisi",
    "city": "Muğla",
    "image_url": "/assets/turizm-bc/boat/boat-2.jpg",
    "price": "14200",
    "sale_price": null,
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.8,
    "review_count": 58,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9012,
    "type": "boat",
    "title": "Marmaris Mavi Ay Yat",
    "slug": "bc-marmaris-mavi-ay-yat",
    "city": "Muğla",
    "image_url": "/assets/turizm-bc/boat/boat-3.jpg",
    "price": "22000",
    "sale_price": "19900",
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.9,
    "review_count": 34,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9013,
    "type": "boat",
    "title": "Fethiye Gulet Turu",
    "slug": "bc-fethiye-gulet-turu",
    "city": "Muğla",
    "image_url": "/assets/turizm-bc/boat/boat-4.jpg",
    "price": "12800",
    "sale_price": null,
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.7,
    "review_count": 91,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9014,
    "type": "boat",
    "title": "Antalya Lüks Motoryat",
    "slug": "bc-antalya-luks-motoryat",
    "city": "Antalya",
    "image_url": "/assets/turizm-bc/boat/boat-5.jpg",
    "price": "16500",
    "sale_price": "15200",
    "price_unit": "gün",
    "star_rating": null,
    "rating": 4.8,
    "review_count": 42,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9015,
    "type": "tour",
    "title": "Kapadokya Balon ve Vadi Turu",
    "slug": "bc-kapadokya-balon-turu",
    "city": "Nevşehir",
    "image_url": "/assets/turizm-bc/tour/tour-1.jpg",
    "price": "2450",
    "sale_price": "2190",
    "price_unit": "kişi",
    "star_rating": null,
    "rating": 4.9,
    "review_count": 412,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9016,
    "type": "tour",
    "title": "İstanbul Tarihi Yarımada Turu",
    "slug": "bc-istanbul-tarihi-yarimada",
    "city": "İstanbul",
    "image_url": "/assets/turizm-bc/tour/tour-2.jpg",
    "price": "1850",
    "sale_price": null,
    "price_unit": "kişi",
    "star_rating": null,
    "rating": 4.7,
    "review_count": 278,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9017,
    "type": "tour",
    "title": "Antalya Şelale & Jeep Safari",
    "slug": "bc-antalya-selale-jeep-safari",
    "city": "Antalya",
    "image_url": "/assets/turizm-bc/tour/tour-3.jpg",
    "price": "1290",
    "sale_price": "1090",
    "price_unit": "kişi",
    "star_rating": null,
    "rating": 4.6,
    "review_count": 156,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9018,
    "type": "tour",
    "title": "Trabzon Yayla Turu",
    "slug": "bc-trabzon-yayla-turu",
    "city": "Trabzon",
    "image_url": "/assets/turizm-bc/tour/tour-4.jpg",
    "price": "1650",
    "sale_price": null,
    "price_unit": "kişi",
    "star_rating": null,
    "rating": 4.8,
    "review_count": 94,
    "is_featured": true,
    "bc_client_fallback": true
  },
  {
    "id": -9019,
    "type": "tour",
    "title": "Bodrum Koy Tekne Turu",
    "slug": "bc-bodrum-koy-turu",
    "city": "Muğla",
    "image_url": "/assets/turizm-bc/tour/tour-5.jpg",
    "price": "1450",
    "sale_price": "1290",
    "price_unit": "kişi",
    "star_rating": null,
    "rating": 4.7,
    "review_count": 203,
    "is_featured": true,
    "bc_client_fallback": true
  }
];

const TYPE_ALIASES: Record<string, string> = { space: "villa", uzay: "villa" };

export function getTourismBcClientFallback(type: string, limit = 24): TourismListingRow[] {
  const t = TYPE_ALIASES[type] || type;
  return BC.filter((l) => l.type === t).slice(0, limit);
}
