import { Router, type IRouter } from "express";
import healthRouter from "./health";
import newsRouter from "./news";
import portalHybridNewsRouter from "./portal-hybrid-news";
import categoriesRouter from "./categories";
import authorsRouter from "./authors";
import rssRouter from "./rss";
import videoRouter from "./video";
import yekGonderRouter from "./yek-gonder";
import videoUserRouter from "./video-user";
import modulesRouter from "./modules";
import adsRouter from "./ads";
import financeRouter from "./finance";
import superligRouter from "./superlig";
import settingsRouter from "./settings";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import ecommerceRouter from "./ecommerce";
import galleriesRouter from "./galleries";
import licensesRouter from "./licenses";
import shopAuthRouter from "./shop-auth";
import shopCheckoutRouter from "./shop-checkout";
import mapRouter from "./map";
import premiumRouter from "./premium";
import wikiRouter from "./wiki";
import membersRouter from "./members";
import sitemapRouter from "./sitemap";
import deliveryRouter from "./delivery";
import partnersRouter from "./partners";
import customerRouter from "./customer";
import transportRouter from "./transport";
import providersRouter from "./providers";
import staffRouter from "./staff";
import chatRouter from "./chat";
import tourismRouter from "./tourism";
import siteContactRouter from "./siteContact";
import careerRouter from "./career";
import mediaRouter from "./media";
import trAddressRouter from "./tr-address";
import supportRouter from "./support";
import broadcastsRouter from "./broadcasts";
import commsHubRouter from "./comms-hub";
import paymentCallbackGuideRouter from "./payment-callback-guide";
import ogHtmlRouter from "./og-html";
import hmRouter from "./hm";
import hmRssNewsRouter from "./hm-rss-news";
import rssBreakingRouter from "./google-news";
import callCenterRouter from "./call-center";
import aiCallRouter from "./ai-call";
import pbxRouter from "./pbx";
import yekpareAiRouter from "./yekpare-ai";
import msbRouter from "./msb";
import vkdCanakkaleSehitleriRouter from "./vkd-canakkale-sehitleri";
import vendorStorefrontRouter from "./vendor-storefront";
import travelRouter from "./travel";
import otomotivRouter from "./otomotiv";
import platformSearchRouter from "./platform-search";
import trendsRouter from "./trends";
import loginCaptchaRouter from "./login-captcha";
import globalMapNewsRouter from "./global-map-news";

const router: IRouter = Router();

router.use(healthRouter);
router.use(ogHtmlRouter);
router.use(paymentCallbackGuideRouter);
router.use(dashboardRouter);
router.use(portalHybridNewsRouter);
router.use(newsRouter);
router.use(categoriesRouter);
router.use(authorsRouter);
router.use(rssRouter);
router.use(videoRouter);
router.use(yekGonderRouter);
router.use(videoUserRouter);
router.use(modulesRouter);
router.use(adsRouter);
router.use(financeRouter);
router.use(superligRouter);
router.use(settingsRouter);
router.use(loginCaptchaRouter);
router.use(mediaRouter);
router.use(aiRouter);
router.use(ecommerceRouter);
router.use(galleriesRouter);
router.use(licensesRouter);
router.use(shopAuthRouter);
router.use(shopCheckoutRouter);
router.use(mapRouter);
router.use(premiumRouter);
router.use(wikiRouter);
router.use("/members", membersRouter);
router.use("/sitemap", sitemapRouter);
router.use(deliveryRouter);
router.use(partnersRouter);
router.use(customerRouter);
router.use(transportRouter);
router.use(providersRouter);
router.use(vendorStorefrontRouter);
router.use(staffRouter);
router.use(chatRouter);
router.use(tourismRouter);
router.use(otomotivRouter);
router.use(platformSearchRouter);
router.use(trendsRouter);
router.use(globalMapNewsRouter);
router.use(travelRouter);
router.use(siteContactRouter);
router.use(careerRouter);
router.use(trAddressRouter);
router.use(supportRouter);
router.use(broadcastsRouter);
router.use(commsHubRouter);
router.use(hmRouter);
router.use(hmRssNewsRouter);
router.use(rssBreakingRouter);
router.use(callCenterRouter);
router.use(aiCallRouter);
router.use(pbxRouter);
router.use(yekpareAiRouter);
router.use(msbRouter);
router.use(vkdCanakkaleSehitleriRouter);

export default router;
