#!/usr/bin/env python3
"""HM panel custom domains -> Traefik (VPS 187.77.84.201). Provisioning executor, 2026-10-08.

Reads TP hm_news_sites (the panel dual-writes every site row there) and writes
/docker/traefik/dynamic/hm-sites-auto.yml with one Host() router per custom domain of an
active NEWS site, so a domain the owner adds in /admin/haber-siteleri reaches the PHP theme
as soon as its DNS points here. <slug>.gundemi.org / <slug>.fix.tc are already covered by the
wildcard routers (gundemi.yml, fixtc-wild.yml). Corporate sites (hmSiteKind=corporate or
corporate vitrin theme / slug) are never routed to the news theme. Hosts that already have a
router anywhere (docker labels, other dynamic files) are skipped. The file is rewritten only
when its content changes (a Traefik reload re-triggers ACME).
Rollback: rm /etc/cron.d/php-theme-hm-domains /docker/traefik/dynamic/hm-sites-auto.yml
"""
import json, os, re, socket, subprocess, sys

OUT = "/docker/traefik/dynamic/hm-sites-auto.yml"
DYN = "/docker/traefik/dynamic"
BLOCK = re.compile(r"(goalgo|turkatav|tukav|pbx|ahenk\.net\.tr|yektube)", re.I)
PLATFORM = re.compile(r"^(?:[a-z0-9-]+\.)?(gundemi\.org|fix\.tc)$")
HOST_RE = re.compile(r"^(?=.{4,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$")
CORP_THEMES = {"corporate", "kurumsal", "vatan"}
CORP_SLUGS = {"vkd", "vatankahramanlari", "trafik", "tr", "tukav"}


def env_url():
    out = subprocess.run(["bash", "-c", ". /root/.hmdb.env && printf %s \"$TP_URL\""], capture_output=True, text=True)
    if not out.stdout:
        sys.exit("TP_URL missing")
    return out.stdout


def rows():
    sql = ("select coalesce(json_agg(json_build_object('id',id,'slug',slug,'d',array[domain,domain2,domain3],"
           "'l',layout_json)),'[]') from hm_news_sites where active = true")
    out = subprocess.run(["psql", env_url(), "-X", "-At", "-c", sql], capture_output=True, text=True, timeout=60)
    if out.returncode != 0:
        sys.exit("psql failed: " + out.stderr[:300])
    return json.loads(out.stdout.strip() or "[]")


def is_corporate(r):
    try:
        l = json.loads(r.get("l") or "{}") if isinstance(r.get("l"), str) else (r.get("l") or {})
    except Exception:
        l = {}
    kind = str(l.get("hmSiteKind") or "").lower()
    if kind == "corporate":
        return True
    if kind == "news":
        return False
    if str(l.get("hmVitrinTheme") or "").lower() in CORP_THEMES:
        return True
    slug = str(r.get("slug") or "").lower()
    return slug in CORP_SLUGS or "vatankahramanlari" in slug or "trafikdernegi" in slug


def existing_hosts():
    hosts = set()
    for f in os.listdir(DYN):
        p = os.path.join(DYN, f)
        if f.endswith((".yml", ".yaml", ".toml")) and p != OUT:
            hosts.update(re.findall(r"Host\(`([^`]+)`\)", open(p).read()))
    ids = subprocess.run(["docker", "ps", "-q"], capture_output=True, text=True).stdout.split()
    if ids:
        lab = subprocess.run(["docker", "inspect", "--format", "{{json .Config.Labels}}"] + ids,
                             capture_output=True, text=True).stdout
        hosts.update(re.findall(r"Host\(`([^`]+)`\)", lab.replace("\\u0060", "`")))
    return {h.lower() for h in hosts}


def resolves(h):
    """Only route hosts whose DNS exists (avoids ACME retries for domains not pointed yet)."""
    try:
        socket.setdefaulttimeout(3)
        return bool(socket.getaddrinfo(h, 443))
    except Exception:
        return False


def main():
    taken = existing_hosts()
    want = {}
    for r in rows():
        if is_corporate(r):
            continue
        for d in r.get("d") or []:
            h = str(d or "").strip().lower().rstrip(".")
            h = re.sub(r"^https?://", "", h).split("/")[0]
            h = re.sub(r"^www\.", "", h)
            if not h or not HOST_RE.match(h) or PLATFORM.match(h) or BLOCK.search(h) or h in taken:
                continue
            if not resolves(h):
                continue
            want[h] = int(r["id"])
    lines = ["# GENERATED by /docker/php-theme/provision/hm-domains-sync.py (cron php-theme-hm-domains). Do not edit.",
             "# Custom domains of active HM news sites (TP hm_news_sites) -> php-theme-yenisafak.", "http:"]
    if want:
        lines.append("  routers:")
        for h in sorted(want):
            key = "hm-auto-" + re.sub(r"[^a-z0-9]+", "-", h)
            lines += [f"    {key}:",
                      f"      rule: \"Host(`{h}`) || Host(`www.{h}`)\"",
                      "      entryPoints: [\"websecure\"]",
                      "      service: hm-auto-php",
                      "      tls:",
                      "        certResolver: letsencrypt",
                      "        domains:",
                      f"          - main: \"{h}\"",
                      "      priority: 15",
                      f"    {key}-http:",
                      f"      rule: \"Host(`{h}`) || Host(`www.{h}`)\"",
                      "      entryPoints: [\"web\"]",
                      "      service: hm-auto-php",
                      "      priority: 15"]
    lines += ["  services:", "    hm-auto-php:", "      loadBalancer:", "        passHostHeader: true",
              "        servers:", "          - url: \"http://127.0.0.1:8095\""]
    body = "\n".join(lines) + "\n"
    old = open(OUT).read() if os.path.exists(OUT) else None
    if old != body:
        tmp = OUT + ".tmp"
        open(tmp, "w").write(body)
        os.replace(tmp, OUT)
        print("updated:", ", ".join(f"{h}(#{i})" for h, i in sorted(want.items())) or "(none)")
    elif "-v" in sys.argv:
        print("unchanged:", ", ".join(sorted(want)) or "(none)")


if __name__ == "__main__":
    main()
