import {
  pgTable,
  integer,
  text,
  boolean,
  numeric,
  timestamp,
  jsonb,
  varchar,
} from "drizzle-orm/pg-core";
import { mapBusinessesTable } from "./haritalar";

export const etkinlikEventCacheTable = pgTable("etkinlik_event_cache", {
  etkinlikId: integer("etkinlik_id").primaryKey(),
  slug: text("slug").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  descriptionHtml: text("description_html"),
  posterUrl: text("poster_url"),
  imageUrls: jsonb("image_urls").notNull().default([]),
  venueName: text("venue_name"),
  venueCity: text("venue_city"),
  venueAddress: text("venue_address"),
  venueLat: numeric("venue_lat"),
  venueLng: numeric("venue_lng"),
  startAt: timestamp("start_at", { withTimezone: true }),
  endAt: timestamp("end_at", { withTimezone: true }),
  timezone: text("timezone").notNull().default("Europe/Istanbul"),
  isFree: boolean("is_free").notNull().default(false),
  minPrice: numeric("min_price"),
  maxPrice: numeric("max_price"),
  currency: text("currency").default("TRY"),
  categoryJson: jsonb("category_json"),
  formatJson: jsonb("format_json"),
  tags: jsonb("tags").notNull().default([]),
  ticketUrl: text("ticket_url"),
  externalUrl: text("external_url").notNull(),
  apiPayload: jsonb("api_payload"),
  scrapedPayload: jsonb("scraped_payload"),
  scrapedAt: timestamp("scraped_at", { withTimezone: true }),
  apiFetchedAt: timestamp("api_fetched_at", { withTimezone: true }),
  /** Haritalar / Sarı Sayfalar map_businesses kaydı */
  mapBusinessId: varchar("map_business_id").references(() => mapBusinessesTable.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
